[build]
builder = "nixpacks"

[build.nixpacksConfig]
npmInstallCmd = "npm install --legacy-peer-deps"

[deploy]
startCommand = "prisma migrate deploy && next start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
